### ISSUE TITLE
Support backwards compatibility with mlrose-hiive

### ISSUE THREAD

**Issue by knakamura13** [knakamura13/mlrose-ky#7]
**Issue Summary**  
Refactored code needs to be further revised to ensure backward compatibility with `mlrose-hiive`.

**Comment by knakamura13** [comment]
## Progress towards supporting backward compatibility
- [ ] Class names
    - [ ] `.algorithms`
        - [ ] `.decay`
            - [x] GeomDecay -> GeometricDecay
            - [ ] ArithDecay -> ArithmeticDecay
            - [ ] ExpDecay -> ExponentialDecay
            - [ ] CustomSchedule -> CustomDecay
        - [ ] `.mutators`
            - [ ] ChangeOneMutator -> SingleGeneMutator
            - [ ] DiscreteMutator -> DiscreteGeneMutator
            - [ ] ShiftOneMutator -> SingleShiftMutator
            - [ ] SwapMutator -> GeneSwapMutator
    - [ ] `.fitness`
        - [ ] TravellingSales -> TravellingSalesperson
    - [ ] `.samples`
        - [ ] SyntheticData -> SyntheticDataGenerator
- [ ] Method names
    - [ ] Requires investigation
- [ ] Method property names
    - [ ] Requires investigation
- [ ] Method returned object/dictionary attributes
    - [ ] Requires investigation

**Comment by knakamura13** [comment]
## Update

I've decided that the classes, methods, properties, and attributes should be renamed back to their original names for the time being. This revision will inherently support backwards compatibility with `mlrose-hiive`.

At this time, only the renamed classes have been documented in the comment above, so we'll start with reverting the class names. 

The other renamed entities will be more difficult to track down, but they might be just as important as the class names.

**Comment by knakamura13** [comment]
@gitongah want me to leave the last two class names for you to rename, or you want me to do it?

**Comment by knakamura13** [comment]
Finished method names check for `.algorithms.decay`.

**Comment by gitongah** [comment]
Finished method name check for .algorithms.crossovers

**Comment by gitongah** [comment]
Finished method name check for .algorithms.mutators all the same with the mlrose-hiive

**Comment by gitongah** [comment]
Finished method name check for the whole algorithms folder and they are the same with mlrose-hiive

**Comment by gitongah** [comment]
Finished method name check for .decorators.short_name_decorator.py we have different names
from the mlrose-hiive

**Comment by gitongah** [comment]
Finished method name check for .fitness and the names match with  mlrose-hiive

**Comment by gitongah** [comment]
Finished method name check for .gridsearch.grid_search_mixin.py we have different name from the mlrose-hiive

**Comment by gitongah** [comment]
Finished method name check  for .runners._nn_runner_base.py and we have a method that is not on the mlrose-hiive.  "dynamic_runner_name" method.
We also have some method name that are different from mlrose-hiive in .runners._runner_base.py

**Comment by knakamura13** [comment]
I'm _reasonably_ satisfied with the level of backwards compatibility at this time, so I'm closing this issue.
